### ISSUE TITLE
Remove unnecessary field injection (autowired annotation)

### ISSUE THREAD

**Issue by phip1611** [JuKu/spring-jwt-authentification#2]
https://github.com/JuKu/spring-jwt-authentification/blob/master/src/main/java/com/jukusoft/authentification/jwt/AuthentificationService.java#L16 

This is redundant. There is already the constructor injection.

**Comment by JuKu** [comment]
@phip1611 Thanks for this issue! :)
This code is a little bit older, as it seems to be. I have reused some old code from older projects (and this code was partly written with a tutorial) and converted it into a new artifact - into this project, so that i can use it for other projects.

But some of the code (e.q. `IAccountService`) is new - and thats how the bad smell came in the code.^^

I will fix this. :)
